INSTALL_SYSTEM=true
INSTALL_REPOSITORIES=true
INSTALL_MULTIMEDIA=true
INSTALL_NVIDIA=true
INSTALL_PACKAGES=true
INSTALL_FLATPAK=true
INSTALL_DAVINCI=true
INSTALL_AUTOSUBS=true
INSTALL_KDE=true
INSTALL_DARKLY=true
INSTALL_TOOLS=true
INSTALL_GAMING=true
RUN_CLEANUP=true
RUN_VERIFY=true
